# Generated by Django 5.1.3 on 2024-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
