# Generated by Django 5.1.3 on 2024-12-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
