# Generated by Django 5.1.3 on 2024-12-09 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tokens', '0002_alter_customtoken_expires_at_alter_customtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 12, 14, 42, 344569, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='token',
            field=models.UUIDField(default='<function uuid4 at 0x000002753BE29260>', unique=True),
        ),
    ]
