# Generated by Django 5.1.3 on 2024-12-09 12:07

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tokens', '0003_alter_customtoken_expires_at_alter_customtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 12, 22, 3, 519433, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
